name: tflite_web
description: Run Tensorflow Lite models on Web with TFLite JS
version: 0.0.1
homepage: https://github.com/hoomanmmd/tflite-web

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  js: ^0.6.4

dev_dependencies:
  flutter_lints: ^2.0.1
  http: ^0.13.5
  test: ^1.22.2
  very_good_analysis: ^3.1.0
